services:
  mysqldb:
    image: mysql:8.0.30
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--host=localhost" ]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

  app-station-ski:
    depends_on:
      mysqldb:
        condition: service_healthy
    image: hassanjlassi23/gestion-station-ski:1.0.0
    restart: on-failure
    ports:
      - 8089:8089
    stdin_open: true
    tty: true

  nginx:
    image: nginx:latest
    ports:
      - 81:80
    restart: unless-stopped

volumes:
  db:
